#
# deploy.yml
#
# Simple deployment of Synse Server & Synse AMT Plugin
#
version: "3"
services:
  synse-server:
    container_name: synse-server
    image: vaporio/synse-server
    environment:
      SYNSE_PLUGIN_TCP: amt-plugin:5001
    ports:
      - 5000:5000
    links:
      - amt-plugin

  amt-plugin:
    container_name: amt-plugin
    image: vaporio/amt-plugin
    ports:
      - 5001:5001
    volumes:
      - ./config/device:/tmp/devices
      - ./scripts:/plugin/scripts
    environment:
      PLUGIN_DEVICE_CONFIG: /tmp/devices
