version: 1.0
locations:
  - name: r1vec
    rack:
      name: rack-1
    board:
      name: vec
devices:
  - name: power
    outputs:
      - type: power.state
    instances:
      - info: VEC power
        location: r1vec
        data:
          ip: "127.0.0.1"
          password: "guest"
